from PyQt6 import QtCore, QtGui, QtWidgets
import style

class Ui_Loading(object):
    def setupUi(self, Loading):
        Loading.setObjectName("Loading")
        Loading.resize(307, 483)
        Loading.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=Loading)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.title_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.title_widget.setObjectName("title_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.title_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(259, 17, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.toolButton = QtWidgets.QToolButton(parent=self.title_widget)
        self.toolButton.setStyleSheet(style.loadWindow.toolButton.value)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Open.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(20, 20))
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.closebutton = QtWidgets.QToolButton(parent=self.title_widget)
        self.closebutton.setStyleSheet(style.loadWindow.closeButton.value)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.closebutton.setIcon(icon1)
        self.closebutton.setIconSize(QtCore.QSize(20, 20))
        self.closebutton.setObjectName("closebutton")
        self.horizontalLayout.addWidget(self.closebutton)
        self.verticalLayout_2.addWidget(self.title_widget)
        self.center_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.center_widget.setStyleSheet(style.loadWindow.center_widget.value)
        self.center_widget.setObjectName("center_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.center_widget)
        self.verticalLayout.setContentsMargins(30, 30, -1, 30)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.portrait = QtWidgets.QLabel(parent=self.center_widget)
        self.portrait.setStyleSheet(style.loadWindow.portrait.value)
        self.portrait.setFixedSize(QtCore.QSize(88, 88))
        self.portrait.setText("")
        self.portrait.setScaledContents(False)
        self.portrait.setObjectName("portrait")
        self.horizontalLayout_2.addWidget(self.portrait)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.ssidlineEdit = QtWidgets.QLineEdit(parent=self.center_widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        self.ssidlineEdit.setFont(font)
        self.ssidlineEdit.setStyleSheet(style.loadWindow.lineEdit.value)
        self.ssidlineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ssidlineEdit.setObjectName("ssidlineEdit")
        self.verticalLayout.addWidget(self.ssidlineEdit)
        self.passworldlineEdit = QtWidgets.QLineEdit(parent=self.center_widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        self.passworldlineEdit.setFont(font)
        self.passworldlineEdit.setStyleSheet(style.loadWindow.lineEdit.value)
        self.passworldlineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.passworldlineEdit.setDragEnabled(False)
        self.passworldlineEdit.setObjectName("passworldlineEdit")
        self.verticalLayout.addWidget(self.passworldlineEdit)
        self.radioButton = QtWidgets.QRadioButton(parent=self.center_widget)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        spacerItem4 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Ignored)
        self.verticalLayout.addItem(spacerItem4)
        self.loading = QtWidgets.QPushButton(parent=self.center_widget)
        self.loading.setEnabled(False)
        self.loading.setAccessibleName("")
        self.loading.setStyleSheet(style.loadWindow.loading.value)
        self.loading.setObjectName("loading")
        self.verticalLayout.addWidget(self.loading)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Ignored)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.scan_codes = QtWidgets.QPushButton(parent=self.center_widget)
        self.scan_codes.setObjectName("scan_codes")
        self.horizontalLayout_4.addWidget(self.scan_codes)
        self.line = QtWidgets.QFrame(parent=self.center_widget)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_4.addWidget(self.line)
        self.morebutton = QtWidgets.QPushButton(parent=self.center_widget)
        self.morebutton.setObjectName("morebutton")
        self.horizontalLayout_4.addWidget(self.morebutton)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addWidget(self.center_widget)
        Loading.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=Loading)
        self.statusbar.setObjectName("statusbar")
        Loading.setStatusBar(self.statusbar)

        self.retranslateUi(Loading)
        QtCore.QMetaObject.connectSlotsByName(Loading)

    def retranslateUi(self, Loading):
        _translate = QtCore.QCoreApplication.translate
        Loading.setWindowTitle(_translate("Loading", "MainWindow"))
        self.toolButton.setText(_translate("Loading", "..."))
        self.closebutton.setText(_translate("Loading", "..."))
        self.ssidlineEdit.setPlaceholderText(_translate("Loading", "输入xx号"))
        self.passworldlineEdit.setPlaceholderText(_translate("Loading", "输入xx密码"))
        self.radioButton.setText(_translate("Loading", "已阅读并同意服务协议和XX隐私保护指引"))
        self.loading.setText(_translate("Loading", "登陆"))
        self.loading.setShortcut(_translate("Loading", "Return"))
        self.scan_codes.setText(_translate("Loading", "扫码登陆"))
        self.morebutton.setText(_translate("Loading", "注册账号"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Loading = QtWidgets.QMainWindow()
    ui = Ui_Loading()
    ui.setupUi(Loading)
    Loading.show()
    sys.exit(app.exec())